---
abstract: 'Build and make available bz2'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Alien::bz2::Installer: '0.01'
  Module::Build: '0.3601'
  Test::More: '0.94'
configure_requires:
  Alien::bz2::Installer: '0.01'
  Module::Build: '0.3601'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-bz2
requires:
  Alien::bz2::Installer: '0.01'
  File::ShareDir: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/plicease/Alien-bz22/issues
  homepage: http://perl.wdlabs.com/Alien-bz2
  repository: git://github.com/plicease/Alien-bz22.git
version: '0.14'
