---
abstract: 'Build and make available libbz2'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::CChecker: 0.05
  Test::More: 0
configure_requires:
  Alien::Base: 0.002
  File::ShareDir: 1.03
  File::Which: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-bz2
requires:
  Alien::Base: 0.002
  Capture::Tiny: 0
  ExtUtils::CChecker: 0
  File::ShareDir: 1.03
  File::Spec: 0
  Text::ParseWords: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/plicease/alien-bz2/issues
  homepage: http://perl.wdlabs.com/Alien-bz2/
  repository: git://github.com/plicease/alien-bz2.git
version: 0.08
